### ISSUE TITLE
Share reference raw data from MAX30102 module

### ISSUE THREAD

**Issue by aziubin** [aromring/MAX30102_by_RF#12]
Hi,

Could you share sample raw data from the module before any processing has been applied please?
This could be .CSV containing MAX30102 output numbers, or .WAV or any other format, which is convenient for you. Having correctly pre-collected data as a reference and comparing them with our data would help to understand if everything OK with schematics and software.

Thanks!
Alexander

**Comment by aromring** [comment]
All right, ExpectedGoodQualitySignals.csv is now a part of this repository.
