### ISSUE TITLE
The question about Relative autocorrelation

### ISSUE THREAD

**Issue by GOKUandVEGET** [aromring/MAX30102_by_RF#16]
According to your description, the relative autocorrelation graph under a good signal should look like this
![Uploading 捕获32.GIF…]()

But when I actually used it, I found that the relative autocorrelation graph of the signals that passed the Pearson correlation coefficient was like this

![3](https://user-images.githubusercontent.com/63447167/82414028-fbecba00-9aa8-11ea-8f0c-0589c515e248.GIF)

Is it necessary to add some filtering means such as moving average filtering

raw data
[DATA.xlsx](https://github.com/aromring/MAX30102_by_RF/files/4655075/DATA.xlsx)

**Comment by aromring** [comment]
All four are perfectly fine autocorrelation plots. In each case the first peak is well pronounced, well above 0.5, with low noise. Its location allows for unambiguous calculation of heart rate. There is nothing wrong with them and filtering is unnecessary.
