### ISSUE TITLE
Heart Rate Stuck at 93

### ISSUE THREAD

**Issue by caferrick** [aromring/MAX30102_by_RF#17]
I reviewed and early post about the Heart Rate stuck at 83. Not sure how it was resolved but my 30102 sensor is Report 93. The SPO2 looks good just the Heart Rate is off

Time[s]	SpO2	HR	Clock	Ratio	Corr
0	5.98	93	0:0:0	0.56	1.00
0	26.58	93	0:0:0	0.75	1.00
0	17.62	93	0:0:0	0.85	1.00
1	26.58	93	0:0:1	0.75	1.00
6	99.26	93	0:0:6	0.81	0.91
6	99.86	93	0:0:6	0.73	0.80
6	93.11	93	0:0:6	0.60	0.96
7	95.67	93	0:0:7	0.77	0.93
8	96.52	93	0:0:8	0.65	0.93
9	98.58	93	0:0:9	0.71	0.98
10	99.03	93	0:0:10	0.76	0.95
10	96.22	93	0:0:10	0.65	0.93
11	95.39	93	0:0:11	0.82	0.95
11	94.23	93	0:0:11	0.83	0.95
12	90.65	93	0:0:12	0.76	0.95
12	92.81	93	0:0:12	0.95	0.96
13	99.54	93	0:0:13	0.88	0.83
13	97.56	93	0:0:13	0.91	0.94
14	99.90	93	0:0:14	0.65	0.98
15	99.08	93	0:0:15	0.58	0.90
15	98.73	93	0:0:15	0.79	0.99
15	90.72	93	0:0:15	0.81	0.93
16	98.96	93	0:0:16	0.84	0.99
17	83.07	93	0:0:17	0.99	0.99
18	94.98	93	0:0:18	0.64	0.99
18	95.53	93	0:0:18	0.77	1.00
20	95.09	93	0:0:20	0.58	0.94
20	97.04	93	0:0:20	0.65	1.00
21	92.96	93	0:0:21	0.94	1.00
21	95.86	93	0:0:21	0.75	1.00
21	97.29	93	0:0:21	0.77	1.00
22	98.09	93	0:0:22	0.78	1.00
22	92.17	93	0:0:22	0.86	0.98
23	94.82	93	0:0:23	0.74	1.00
23	96.86	93	0:0:23	0.75	1.00
24	98.21	93	0:0:24	0.77	1.00
24	99.28	93	0:0:24	0.76	1.00
26	99.42	93	0:0:26	0.70	0.85
26	98.07	93	0:0:26	0.93	0.86
27	93.19	93	0:0:27	0.85	0.98
29	99.91	93	0:0:29	0.54	0.94
31	99.74	93	0:0:31	0.63	0.93
33	99.49	93	0:0:33	0.95	0.87
33	99.19	93	0:0:33	0.67	1.00
34	97.84	93	0:0:34	0.89	0.95
34	99.88	93	0:0:34	0.89	0.91
35	98.91	93	0:0:35	0.58	0.92
37	99.02	93	0:0:37	0.72	0.91
38	98.38	93	0:0:38	1.00	0.98
38	96.92	93	0:0:38	0.54	0.97
40	98.48	93	0:0:40	1.02	0.95
41	99.39	93	0:0:41	0.99	0.94
42	98.65	93	0:0:42	0.92	0.97
43	98.91	93	0:0:43	0.55	0.97
43	98.69	93	0:0:43	0.59	0.90
43	99.39	93	0:0:43	0.73	0.88
44	98.80	93	0:0:44	0.65	0.87
44	99.51	93	0:0:44	0.81	0.90
45	98.38	93	0:0:45	0.95	1.00
46	99.21	93	0:0:46	0.91	0.99
47	99.30	93	0:0:47	0.97	0.99
48	95.59	93	0:0:48	0.85	0.99
49	83.87	93	0:0:49	0.85	1.00
49	83.68	93	0:0:49	0.75	1.00
49	84.82	93	0:0:49	0.84	1.00
50	98.40	93	0:0:50	0.84	0.99
50	84.16	93	0:0:50	0.68	0.99
51	79.73	93	0:0:51	0.73	1.00
51	76.69	93	0:0:51	0.66	0.99
52	77.12	93	0:0:52	0.53	0.99
52	85.53	93	0:0:52	0.53	0.99
52	90.90	93	0:0:52	0.54	0.94
53	70.04	93	0:0:53	0.84	0.87
53	97.72	93	0:0:53	1.01	0.91
57	95.19	93	0:0:57	0.75	0.86
70	87.25	93	0:1:10	0.68	0.88
72	99.96	93	0:1:12	0.89	0.90
73	99.95	93	0:1:13	0.75	0.84
102	97.36	93	0:1:42	0.87	0.95
102	89.99	93	0:1:42	0.67	1.00
102	86.68	93	0:1:42	0.63	0.99
103	70.56	93	0:1:43	0.50	0.94
104	86.80	93	0:1:44	0.79	0.88
105	89.36	93	0:1:45	0.77	0.82
107	96.46	93	0:1:47	0.65	0.90
118	92.20	93	0:1:58	0.72	0.82
119	87.88	93	0:1:59	0.65	0.84
150	88.46	93	0:2:30	0.56	0.84
185	90.86	93	0:3:5	0.91	0.98
186	96.07	93	0:3:6	0.53	0.93
186	82.33	93	0:3:6	0.82	0.95
186	96.22	93	0:3:6	0.54	0.83
187	99.40	93	0:3:7	0.90	0.86
208	34.77	93	0:3:28	0.58	0.88
218	94.83	93	0:3:38	0.67	0.90
218	95.05	93	0:3:38	0.78	0.88
219	61.99	93	0:3:39	0.86	0.83
226	95.69	93	0:3:46	0.55	0.85
237	92.92	93	0:3:57	0.92	0.97
237	90.59	93	0:3:57	0.82	0.99
238	96.78	93	0:3:58	0.83	0.88
239	75.07	93	0:3:59	0.81	0.94
240	62.97	93	0:4:0	0.88	0.90
241	79.74	93	0:4:1	0.76	0.95
242	96.11	93	0:4:2	0.87	0.93
243	95.96	93	0:4:3	0.73	0.92
251	84.73	93	0:4:11	0.68	0.91
252	91.68	93	0:4:12	0.54	0.80
253	95.51	93	0:4:13	0.80	0.89

**Comment by aromring** [comment]
Issue #8 has been resolved: HR was stuck at 83 due to faulty hardware. Please read all details here: https://github.com/aromring/MAX30102_by_RF/issues/8
If you still think your hardware is perfect, then you'll need to follow the standard bug reporting routine:
"Please open the README file here https://github.com/aromring/MAX30102_by_RF/blob/master/README.md
scroll down to HOW TO REPORT BUGS section and follow instructions therein."
