### ISSUE TITLE
File names and case sensitivity

### ISSUE THREAD

**Issue by mgaman** [aromring/MAX30102_by_RF#19]
I just took your code and repurposed it in a Linux/Visual Studio Code environment. It is quite a simple process as follows:
1. The *.ino file is renamed to main.cpp
2. The header files are moved to the "include" directory.
3. In Linux files names are case-sensitive (unlike Windows). So references to <arduino.h> must be rewritten as <Arduino.h>

You mention pin 10 as an interrupt pin without using it as an interrupt at all, rather as just GPIO. This may account for sampling problems.
I shall try and adjust the code to work with true interrupts.

**Comment by aromring** [comment]
Thank you.
