### ISSUE TITLE
min_autocorrelation_ratio = 0.5???

### ISSUE THREAD

**Issue by GOKUandVEGET** [aromring/MAX30102_by_RF#24]
The calculated heart rate obtained by your algorithm is half of the actual heart rate, and the first local maximum of its relative autocorrelation is 0.29.

RAW IR DATA. 50Hz 3s
129650	129663	129675	129702	129688	129667	129666	129677	129648	129575	129485	129453	129461	129485	129506	129542	129565	129562	129583	129611	129624	129614	129602	129588	129614	129652	129672	129677	129679	129707	129710	129689	129708	129750	129763	129749	129751	129764	129780	129792	129782	129775	129782	129797	129782	129719	129640	129598	129596	129613	129615	129641	129657	129683	129696	129694	129703	129702	129693	129682	129668	129704	129719	129737	129735	129735	129752	129754	129756	129729	129746	129748	129759	129751	129752	129757	129750	129730	129723	129656	129583	129529	129511	129539	129537	129546	129574	129604	129624	129665	129690	129682	129685	129698	129712	129728	129743	129771	129781	129804	129785	129799	129805	129823	129839	129851	129864	129897	129902	129899	129881	129913	129920	129931	129927	129920	129927	129936	129941	129923	129885	129809	129766	129713	129730	129740	129763	129791	129819	129813	129817	129834	129842	129816	129810	129810	129806	129825	129846	129869	129909	129904	129905	129900	129917	129951	129973	129941	129959	129977

**Comment by aromring** [comment]
![image](https://user-images.githubusercontent.com/13855881/104225325-18a07e00-53fb-11eb-9039-d260702d9e3e.png)
It's not a bug, it's a garbage signal (see above) which should be rejected as the code does, rightfully, at the min_autocorrelation_ratio = 0.5 level.

Now, while we are at it, it takes me quite some time to copy the raw data from postings, reformat it, add sample column, etc., - all for the sake of creating plots in Excel. Only to show you, for the n-th time, something you should have looked at yourself before posting. Thus, I have clarified point B in the "[HOW TO REPORT BUGS](https://github.com/aromring/MAX30102_by_RF/blob/master/README.md)" instructions: From now on, I will reject reports that don't contain plots of all relevant signals.
