### ISSUE TITLE
I cant found more detail sensor settings, problems with get values

### ISSUE THREAD

**Issue by sjsivo** [aromring/MAX30102_by_RF#25]
BPM and SPO2 Values are not valid for my sensor MAX30102 and ESP32.
Used more types of algoritm and result is not valid BPM and SPO2 values.
How can i correct?

[
![mess1](https://user-images.githubusercontent.com/32570557/109292314-79a8d780-782a-11eb-95af-722995cbdd16.png)
![mess2](https://user-images.githubusercontent.com/32570557/109292316-7a416e00-782a-11eb-8a99-0eb9133dbfd9.png)
![mess3](https://user-images.githubusercontent.com/32570557/109292317-7ada0480-782a-11eb-9384-aeabe63b58fd.png)
![mess4](https://user-images.githubusercontent.com/32570557/109292318-7ada0480-782a-11eb-9289-08a197806f10.png)

](url)

**Comment by aromring** [comment]
You can start by explaining what you exactly mean by "BPM and SPO2 Values are not valid" and what the blue and red curves represent. Thank you for the graphs, by the way.

**Comment by sjsivo** [comment]
I reading the IR and Red diode values from Max30102 sensor on ESP32 chip.
Red and blue are values from this 2 lights from Max chip showed in Serial Plotter.
I mean: algoritm can not recognize that some heartbeat come and can not calculate SPO2. Base on Current and lightning from diods recognize sometimes that BPM can calculate sometimes, but much more times are values not valid.
With this i mean is, that on display or in Serial communication ,algoritm showed values "-999" and notvalid variable are set. 
Can i change default settings for el. current to diods and retest with more different settings?
I cant read good values from original Maxim algoritm too.
How cann i correct this situation?

**Comment by sjsivo** [comment]
I have change more times ir and red current values in max30102.cpp
. Still i have no luck to measure SPO2. BPM is sometimes shown correctly now.

![measure5](https://user-images.githubusercontent.com/32570557/109384559-f51f8d00-78ed-11eb-98cd-508853951e06.png)
![changedvalues](https://user-images.githubusercontent.com/32570557/109384560-f5b82380-78ed-11eb-8eb9-60900d67ad30.png)

**Comment by sjsivo** [comment]
In algorithm_by_RF.cpp was checked xy_ratio too...

Last measured values here:

[valuesMeasured.txt](https://github.com/aromring/MAX30102_by_RF/files/6054237/valuesMeasured.txt)

**Comment by aromring** [comment]
Ah, yes. Thank you for providing the xy_ratio - this saves days of e-mail exchanges. High values of this parameter clearly indicate a well known problem: you are using a cheap clone of MAX30102 in which the IR and RED channels are swapped. See issue #13 for more details:
https://github.com/aromring/MAX30102_by_RF/issues/13#issue-601473302

**Comment by sjsivo** [comment]
Now is good.
Its measure correctly with original values too.
I changed:
 for(i=0;i<BUFFER_SIZE;i++)
  {
    while(digitalRead(oxiInt)==1);  //wait until the interrupt pin asserts
    maxim_max30102_read_fifo( (aun_ir_buffer+i),(aun_red_buffer+i));  //read from MAX30102 FIFO //swap values for cheap modules!!!

in your sample code and works correctly.
Thank for your helpful support.
