### ISSUE TITLE
if (!sensor.begin())

### ISSUE THREAD

**Issue by gallaugher** [aromring/MAX30102_by_RF#27]
I am likely missing something very basic - so sorry, I'm still quite new at this. I've downloaded the repo & opened the MAX30100_Tester sketch, but when I try to compile I get an error on line 34:
if (!sensor.begin())
could not convert 'sensor.MAX30100::begin(pw1600, i50, sr100)' from 'void' to 'bool'

I've otherwise gotten Feather M0 code to compile on this board. I'm trying to find a way to modify Jiri Praus's Beating Heart Sculpture (which uses a MAX30100) so that it can work with a Feather. I have the LEDs lighting, but haven't yet been able to get the MAX30100 to work with the Feather M0. I was hoping your code would help me at least confirm the sensor was working, but I can't seem to get this running. Again - apologies for newbie gaffe I've likely committed. Thanks for sharing your code. There's not much out there on Feather M0 & MAX30100.

**Comment by aromring** [comment]
"MAX30100_Tester sketch"? There is no such sketch in this repository. Neither it has this line of code: "if (!sensor.begin())" ("line 34").
Are you sure you are posting this to the right GitHub page?
