### ISSUE TITLE
Are we confident enough in the data coming from the board? 

### ISSUE THREAD

**Issue by kwende** [aromring/MAX30102_by_RF#5]
Greetings - 

I was trying to find your email so that I could ask this directly, but I cannot find it so I thought I'd open an issue. I'm not reporting a bug for your software, but mostly curious about an observation I've had when using the board, and also when observing the data plots (yours included). 

Namely this: the flat line for heart rate and SPO2 seem just plain wrong. Heart rate varies quite a bit during sleep, in fact, there should be a "saddle" effect that occurs when you're sleeping properly. Also, during REM sleep, breathing rate and heart rate also increase. In the data plot you're showing (https://www.instructables.com/id/Pulse-Oximeter-With-Much-Improved-Precision/), it's a straight line with what seems to be noise about it. I understand it might be how it looks due to scale, but it doesn't look like the type of heart patterns I've come to know as indicative of sleep cycles, etc. 

I have a belief I might have sleep apnea, so I bought one of these boards. I used the "noisy" version of the software provided by the manufacturer but noticed my SPO2 was constant throughout the entire night at nearly 97. This was suspect for me. 

Do we know for sure the data coming off these boards are even right? Both oxygen and heart rate should vary more than what I see when observing my data plots as well as that of others. I thus have a great deal of suspicion about how well these boards even function. Do you have any reason to believe at least the SPO2 signal is anything more than a constant number with random noise? 

My data plot: 

![image](https://user-images.githubusercontent.com/526471/57781277-77c26280-76ef-11e9-8579-868e89b9dde3.png)

**Comment by boblongoria** [comment]
I am also interested in this issue but lacking in technical expertise. Regards Bob

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by kwende** [comment]
I've since realized the author is communicating with people on his Instructables article. I've closed this comment.

**Comment by aromring** [comment]
I've posted the answer in my Instructable.
