### ISSUE TITLE
Cool. Can I link two MAX30102 sensor by this code?

### ISSUE THREAD

**Issue by timeanddoctor** [aromring/MAX30102_by_RF#7]
Dear Professor,

I want to connect two MAX30102 sensor for  SPO2 with an Arduino UNO, I donnot know How to chang this code ,could you help me.
Thanks.

**Comment by sergiocntr** [comment]
At first,can you change the i2c address on your max30102 module? ( Es. Soldering two pads ) If you can , the lib can be adjusted/ modified as class and using multiple instances that can be achieved.

**Comment by aromring** [comment]
Although it's possible to put multiple devices on the I2C bus, as @sergiocntr suggests, I am afraid the Arduino Uno CPU is not powerful enough to handle two sensors at once. It can barely handle a single one, as it is.
